### ISSUE TITLE
error on  diode-agent with Dell OS10 napalm drivers 

### ISSUE THREAD

**Issue by MarkGraham99** [netboxlabs/diode#187] opened 2024-10-15 18:00 UTC
error occurs when trying to run data for dell  S5224F switch.  installed napalm-dellos10  (current version)   dell os 10.5.5.5 

`ERROR:diode_napalm.cli.cli:Error while processing policy discovery_1: Value out of range: 25000000000`

able to confirm that python can connect and pull data with napalm-dellos10 

python output :

>>> from napalm.base import get_network_driver
>>> d = get_network_driver('dellos10')
>>> e = d('x.x.x.x', 'username', 'password', optional_args={'global_delay_factor': 3})
>>> e.open()

>>> e.get_facts()
{'uptime': 516184, 'vendor': 'Dell', 'os_version': '10.5.5.5', 'serial_number': 'xxxxxxxx', 'model': 'S5224F-ON', 'hostname': 'xxxxxxx', 'fqdn': 'N/A', 'interface_list': ['ethernet1/1/1', 'ethernet1/1/2', 'ethernet1/1/3', 'ethernet1/1/4', 'ethernet1/1/5', 'ethernet1/1/6', 'ethernet1/1/7', 'ethernet1/1/8', 'ethernet1/1/9', 'ethernet1/1/10', 'ethernet1/1/11', 'ethernet1/1/12', 'ethernet1/1/13', 'ethernet1/1/14', 'ethernet1/1/15', 'ethernet1/1/16', 'ethernet1/1/17', 'ethernet1/1/18', 'ethernet1/1/19', 'ethernet1/1/20', 'ethernet1/1/21:1', 'ethernet1/1/22:1', 'ethernet1/1/23:1', 'ethernet1/1/24:1', 'ethernet1/1/25', 'ethernet1/1/26', 'ethernet1/1/27', 'ethernet1/1/28', 'mgmt1/1/1', 'vlanx', 'vlanx', 'vlanx', 'vlanx', 'vlanx', 'vlanx', 'port-channelx', 'port-channelx', 'port-channelx', 'port-channelx', 'null0']}
(removed some config data)  

>>> e.get_interfaces()
{'ethernet1/1/1': {'last_flapped': 166026.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:55', 'is_up': True, 'speed': 25000000000}, 'ethernet1/1/2': {'last_flapped': 172673.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:02', 'is_up': True, 'speed': 25000000000}, 'ethernet1/1/3': {'last_flapped': 166805.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:03', 'is_up': True, 'speed': 25000000000}, 'ethernet1/1/4': {'last_flapped': 179985.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:04', 'is_up': True, 'speed': 25000000000}, 'ethernet1/1/5': {'last_flapped': 134.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:05', 'is_up': True, 'speed': 25000000000}, 'ethernet1/1/6': {'last_flapped': 81561.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:06', 'is_up': True, 'speed': 25000000000}, 'ethernet1/1/7': {'last_flapped': 29.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:07', 'is_up': False, 'speed': 0}, 'ethernet1/1/8': {'last_flapped': 29.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:08', 'is_up': False, 'speed': 0}, 'ethernet1/1/9': {'last_flapped': 29.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:09', 'is_up': False, 'speed': 0}, 'ethernet1/1/10': {'last_flapped': 29.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:0a', 'is_up': False, 'speed': 0}, 'ethernet1/1/11': {'last_flapped': 30.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:0b', 'is_up': False, 'speed': 0}, 'ethernet1/1/12': {'last_flapped': 30.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:0c', 'is_up': False, 'speed': 0}, 'ethernet1/1/13': {'last_flapped': 30.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:0d', 'is_up': False, 'speed': 0}, 'ethernet1/1/14': {'last_flapped': 30.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:0e', 'is_up': False, 'speed': 0}, 'ethernet1/1/15': {'last_flapped': 30.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:0f', 'is_up': False, 'speed': 0}, 'ethernet1/1/16': {'last_flapped': 30.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:10', 'is_up': False, 'speed': 0}, 'ethernet1/1/17': {'last_flapped': 30.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:11', 'is_up': False, 'speed': 0}, 'ethernet1/1/18': {'last_flapped': 30.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:12', 'is_up': False, 'speed': 0}, 'ethernet1/1/19': {'last_flapped': 30.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:13', 'is_up': False, 'speed': 0}, 'ethernet1/1/20': {'last_flapped': 30.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:14', 'is_up': False, 'speed': 0}, 'ethernet1/1/21:1': {'last_flapped': 31.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:15', 'is_up': False, 'speed': 0}, 'ethernet1/1/22:1': {'last_flapped': 31.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:16', 'is_up': False, 'speed': 0}, 'ethernet1/1/23:1': {'last_flapped': 31.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:17', 'is_up': False, 'speed': 0}, 'ethernet1/1/24:1': {'last_flapped': 78831.0, 'description': '', 'is_enabled': False, 'mac_address': '20:88:10:44:cf:18', 'is_up': False, 'speed': 0}, 'ethernet1/1/25': {'last_flapped': 36.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:19', 'is_up': True, 'speed': 100000000000}, 'ethernet1/1/26': {'last_flapped': 36.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:1d', 'is_up': True, 'speed': 100000000000}, 'ethernet1/1/27': {'last_flapped': 31.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:21', 'is_up': False, 'speed': 0}, 'ethernet1/1/28': {'last_flapped': 31.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:25', 'is_up': False, 'speed': 0}, 'mgmt1/1/1': {'last_flapped': 31.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:00', 'is_up': False, 'speed': 0}, 'vlanx': {'last_flapped': 43.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:51', 'is_up': True, 'speed': 10000000000}, 'vlanx': {'last_flapped': 173835.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:51', 'is_up': True, 'speed': 10000000000}, 'vlanx': {'last_flapped': 75988.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:51', 'is_up': True, 'speed': 10000000000}, 'vlanx': {'last_flapped': 43.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:51', 'is_up': True, 'speed': 10000000000}, 'vlanx': {'last_flapped': 43.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:51', 'is_up': True, 'speed': 10000000000}, 'vlanx': {'last_flapped': 36.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:51', 'is_up': True, 'speed': 10000000000}, 'port-channelx': {'last_flapped': 78832.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:29', 'is_up': False, 'speed': 0}, 'port-channelx': {'last_flapped': 136.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:2b', 'is_up': True, 'speed': 25000000000}, 'port-channelx': {'last_flapped': 81641.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:2c', 'is_up': True, 'speed': 25000000000}, 'port-channelx': {'last_flapped': 36.0, 'description': '', 'is_enabled': True, 'mac_address': '20:88:10:44:cf:7e', 'is_up': True, 'speed': 200000000000}, 'null0': {'last_flapped': 31.0, 'description': '', 'is_enabled': True, 'mac_address': '', 'is_up': True, 'speed': -1}}

**Comment by leoparente** [comment] 2024-10-15 19:27
Thanks @MarkGraham99 for opening the ticket. I thought that the issue would be on the SDK part because it requires `int32` for interface speed and the provided values like 25000000000 overflows it. However, the value is not accepted in netbox as well. 
![image](https://github.com/user-attachments/assets/ea86a1f1-0062-4431-95eb-6b65af214a52)


The reason is what you have explained: the value returned is in bps and netbox expects kbps; That said, the fix need to come from napalm agent side to properly match the value with the expected SDK/NetBox value.

**Comment by leoparente** [comment] 2024-10-17 13:21
@MarkGraham99 The best solution in our side at least is to ignore when the overflows occurs and was the fix that we did on agent on https://github.com/netboxlabs/diode-agent/pull/15

The issue **root cause** is in dellos10 napalm driver and there is actually a fix already there: https://github.com/napalm-automation-community/napalm-dellos10/pull/29 but it's not been released. A way to overcome this is to install the latest driver by yourself:

```
git clone https://github.com/napalm-automation-community/napalm-dellos10.git
pip install napalm-dellos10/ --no-cache-dir
```

With that said, I'm closing this ticket. Thanks

**Closed as completed by leoparente** 2024-10-17 13:21 UTC
Labels: bug, diode-agent
